### ISSUE TITLE
Error while converting keras model to tflite.

### ISSUE THREAD

**Issue by j22054022** [Kazuhito00/hand-gesture-recognition-using-mediapipe#8]
after following: keypoint_classification.ipynb
got error while converting .hdf5 to .tflite
```
...
Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       317
           1       1.00      1.00      1.00       329

    accuracy                           1.00       646
   macro avg       1.00      1.00      1.00       646
weighted avg       1.00      1.00      1.00       646

2022-07-13 00:07:33.159140: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:362] Ignored output_format.
2022-07-13 00:07:33.159164: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:365] Ignored drop_control_dependency.
2022-07-13 00:07:33.159600: I tensorflow/cc/saved_model/reader.cc:45] Reading SavedModel from: /tmp/tmpe_iawth6
2022-07-13 00:07:33.160549: I tensorflow/cc/saved_model/reader.cc:89] Reading meta graph with tags { serve }
2022-07-13 00:07:33.160564: I tensorflow/cc/saved_model/reader.cc:130] Reading SavedModel debug info (if present) from: /tmp/tmpe_iawth6
2022-07-13 00:07:33.163551: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
2022-07-13 00:07:33.164236: I tensorflow/cc/saved_model/loader.cc:229] Restoring SavedModel bundle.
2022-07-13 00:07:33.190545: I tensorflow/cc/saved_model/loader.cc:213] Running initialization op on SavedModel bundle at path: /tmp/tmpe_iawth6
2022-07-13 00:07:33.196456: I tensorflow/cc/saved_model/loader.cc:305] SavedModel load for tags { serve }; Status: success: OK. Took 36862 microseconds.
2022-07-13 00:07:33.208658: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
WARNING:absl:Buffer deduplication procedure will be skipped when flatbuffer library is not properly loaded
Traceback (most recent call last):
  File "handsign_train.py", line 94, in <module>
    tflite_quantized_model = converter.convert()
  File "/home/jason/hand-gesture-recognition-using-mediapipe/venv/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 930, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
  File "/home/jason/hand-gesture-recognition-using-mediapipe/venv/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 922, in _convert_and_export_metrics
    return flatbuffer_utils.convert_object_to_bytearray(model_object)
  File "/home/jason/hand-gesture-recognition-using-mediapipe/venv/lib/python3.8/site-packages/tensorflow/lite/tools/flatbuffer_utils.py", line 84, in convert_object_to_bytearray
    model_offset = model_object.Pack(builder)
  File "/home/jason/hand-gesture-recognition-using-mediapipe/venv/lib/python3.8/site-packages/tensorflow/lite/python/schema_py_generated.py", line 11662, in Pack
    operatorCodes = builder.EndVector()
TypeError: EndVector() missing 1 required positional argument: 'vectorNumElems'
```
> handsign_train.py has the same code as keypoint_classification.ipynb

package:
`tensorflow 2.9.1`
`tf-nightly 2.10.0.dev20220710`  
`flatbuffers 1.12 `

**Comment by PINTO0309** [comment]
It's a problem specific to your environment. `tf` and `tf-nightly` should never coexist.
```bash
$ xhost +local: && \
docker run --gpus all -it --rm \
-v `pwd`:/home/user/workdir \
-v /tmp/.X11-unix/:/tmp/.X11-unix:rw \
--device /dev/video0:/dev/video0:mwr \
--net=host \
-e XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR \
-e DISPLAY=$DISPLAY \
--privileged \
ghcr.io/pinto0309/openvino2tensorflow:latest

$ sudo pip3 install jupyter seaborn
$ jupyter notebook keypoint_classification.ipynb
```
![image](https://user-images.githubusercontent.com/33194443/178615428-366f0cfd-46ec-4b23-b21b-33ca97abfe85.png)


- tf-nightly cleaning
```bash
$ sudo pip3 uninstall -y \
tensorboard-plugin-wit tb-nightly tensorboard \
tf-estimator-nightly tensorflow-gpu \
tensorflow tf-nightly tensorflow_estimator

$ pip3 install tensorflow
```

**Comment by j22054022** [comment]
it work after I recreated a venv without tf-nightly installed, thanks
